In [1]:
#Importing packages
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.colors as colors
import datetime
import seaborn as sns
import math

import joblib

print("Libraries imported!")

Libraries imported!

## Finding similar movies

In [2]:
r_cols = ['user_id', 'movie_id', 'rating']

ratings = pd.read_csv('data/ml-latest-small/ratings.csv')

m_cols = ['movie_id', 'title']
movies = pd.read_csv('data/ml-latest-small/movies.csv')

ratings_df = pd.merge(movies, ratings)

ratings_df = ratings_df[['movieId', 'title', 'userId', 'rating']]

ratings_df.head()

   movieId             title  userId  rating
0        1  Toy Story (1995)       1     4.0
1        1  Toy Story (1995)       5     4.0
2        1  Toy Story (1995)       7     4.5
3        1  Toy Story (1995)      15     2.5
4        1  Toy Story (1995)      17     4.5

In [3]:
ratings_df[ratings_df.title.str.contains('Pulp Fiction')]

      movieId                title  userId  rating
7860      296  Pulp Fiction (1994)       1     3.0
7861      296  Pulp Fiction (1994)       4     1.0
7862      296  Pulp Fiction (1994)       5     5.0
7863      296  Pulp Fiction (1994)       6     2.0
7864      296  Pulp Fiction (1994)       8     4.0
...       ...                  ...     ...     ...
8162      296  Pulp Fiction (1994)     606     5.0
8163      296  Pulp Fiction (1994)     607     3.0
8164      296  Pulp Fiction (1994)     608     5.0
8165      296  Pulp Fiction (1994)     609     4.0
8166      296  Pulp Fiction (1994)     610     5.0

[307 rows x 4 columns]

In [4]:
movie_ratings = ratings_df.pivot_table(index=['userId'], columns=['title'], values='rating')

movie_ratings.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]Â² (2009),[REC]Â³ 3 GÃ©nesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),Â¡Three Amigos! (1986),Ã€ nous la libertÃ© (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
pulp_fiction_ratings = movie_ratings['Pulp Fiction (1994)']
pulp_fiction_ratings.head()

userId
1    3.0
2    NaN
3    NaN
4    1.0
5    5.0
Name: Pulp Fiction (1994), dtype: float64

In [6]:
similar_movies = movie_ratings.corrwith(pulp_fiction_ratings)
similar_movies.dropna(inplace=True)
df = pd.DataFrame(similar_movies)
print(df.shape)
df.head(10)

(4878, 1)

                                                           0
title
'burbs, The (1989)                                 -0.187323
(500) Days of Summer (2009)                        -0.044034
*batteries not included (1987)                     -0.738549
...And Justice for All (1979)                      -0.188982
10 Cent Pistol (2015)                               1.000000
10 Cloverfield Lane (2016)                         -0.201347
10 Things I Hate About You (1999)                  -0.126206
10,000 BC (2008)                                   -0.409514
101 Dalmatians (1996)                               0.289800
101 Dalmatians (One Hundred and One Dalmatians)...  0.044441

Let's sort the results and see the similar movies....

In [7]:
similar_movies.sort_values(ascending=False).head(30)

title
Underground (1995)                                                            1.0
In-Laws, The (2003)                                                           1.0
Eddie the Eagle (2016)                                                        1.0
Wings of the Dove, The (1997)                                                 1.0
After Life (Wandafuru raifu) (1998)                                           1.0
Thieves (Voleurs, Les) (1996)                                                 1.0
First Snow (2006)                                                             1.0
MisÃ©rables, Les (2000)                                                        1.0
Brave Little Toaster, The (1987)                                              1.0
Intimate Strangers (Confidences trop intimes) (2004)                          1.0
Brave One, The (2007)                                                         1.0
Meet the Spartans (2008)                                                      1.0
Death Wish 3 (1985)                                                           1.0
Tuck Everlasting (2002)                                                       1.0
Hoodwinked! (2005)                                                            1.0
Hope Floats (1998)                                                            1.0
Klute (1971)                                                                  1.0
Ugetsu (Ugetsu monogatari) (1953)                                             1.0
Virgin Spring, The (JungfrukÃ¤llan) (1960)                                     1.0
Wolf Children (Okami kodomo no ame to yuki) (2012)                            1.0
Maxed Out: Hard Times, Easy Credit and the Era of Predatory Lenders (2006)    1.0
Wolfman, The (2010)                                                           1.0
Luxo Jr. (1986)                                                               1.0
Claymation Christmas Celebration, A (1987)                                    1.0
Max Dugan Returns (1983)                                                      1.0
Highway 61 (1991)                                                             1.0
Boiling Point (1993)                                                          1.0
Looking for Richard (1996)                                                    1.0
Azumi (2003)                                                                  1.0
Song of the Little Road (Pather Panchali) (1955)                              1.0
dtype: float64

The results don't make sense...:( Let's think about it for a moment... <br />
There are people who watched Pulp Fiction (PF) and other obscure movies that don't align with our interests. Clearly those recommendations would be good for them, but not for all of us. So let's dig deep dive into it.

First, let's get rid of movies that were only watched by a few people. Very small sample of ratings would skew our results.

In [8]:
movie_stats = ratings_df.groupby('title').agg({'rating': [np.size, np.mean]})
movie_stats

                                          rating
                                            size      mean
title
'71 (2014)                                   1.0  4.000000
'Hellboy': The Seeds of Creation (2004)      1.0  4.000000
'Round Midnight (1986)                       2.0  3.500000
'Salem's Lot (2004)                          1.0  5.000000
'Til There Was You (1997)                    2.0  4.000000
...                                          ...       ...
eXistenZ (1999)                             22.0  3.863636
xXx (2002)                                  24.0  2.770833
xXx: State of the Union (2005)               5.0  2.000000
Â¡Three Amigos! (1986)                       26.0  3.134615
Ã€ nous la libertÃ© (Freedom for Us) (1931)    1.0  1.000000

[9719 rows x 2 columns]

In [9]:
movie_stats[movie_stats['rating']['size'] >= 100].sort_values([('rating', 'mean')], ascending=False).head()

                                 rating
                                   size      mean
title
Shawshank Redemption, The (1994)  317.0  4.429022
Godfather, The (1972)             192.0  4.289062
Fight Club (1999)                 218.0  4.272936
Godfather: Part II, The (1974)    129.0  4.259690
Departed, The (2006)              107.0  4.252336

In [10]:
df = movie_stats[movie_stats['rating']['size'] >= 50].join(pd.DataFrame(similar_movies, columns=['similarity']))
df

                                   (rating, size)  (rating, mean)  similarity
title
10 Things I Hate About You (1999)            54.0        3.527778   -0.126206
12 Angry Men (1957)                          57.0        4.149123   -0.048795
2001: A Space Odyssey (1968)                109.0        3.894495    0.117497
28 Days Later (2002)                         58.0        3.974138   -0.008989
300 (2007)                                   80.0        3.681250    0.192834
...                                           ...             ...         ...
X2: X-Men United (2003)                      76.0        3.723684   -0.011742
You've Got Mail (1998)                       50.0        3.120000   -0.057161
Young Frankenstein (1974)                    69.0        3.992754    0.075178
Zombieland (2009)                            53.0        3.877358   -0.120496
Zoolander (2001)                             54.0        3.509259    0.227247

[450 rows x 3 columns]

In [24]:
df.sort_values(['similarity'], ascending=False)[1:6]

                                 (rating, size)  (rating, mean)  similarity
title
Wolf of Wall Street, The (2013)            54.0        3.916667    0.579915
Fight Club (1999)                         218.0        4.272936    0.543465
Kill Bill: Vol. 1 (2003)                  131.0        3.961832    0.504147
Interstellar (2014)                        73.0        3.993151    0.503411
True Romance (1993)                        65.0        3.800000    0.484209

## Item-based Collaborative Filtering

In [12]:
ratings_df.head()

   movieId             title  userId  rating
0        1  Toy Story (1995)       1     4.0
1        1  Toy Story (1995)       5     4.0
2        1  Toy Story (1995)       7     4.5
3        1  Toy Story (1995)      15     2.5
4        1  Toy Story (1995)      17     4.5

In [13]:
user_ratings = ratings_df.pivot_table(index=['userId'], columns=['title'], values='rating')
user_ratings.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]Â² (2009),[REC]Â³ 3 GÃ©nesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),Â¡Three Amigos! (1986),Ã€ nous la libertÃ© (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
corr_matrix = user_ratings.corr()
corr_matrix.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]Â² (2009),[REC]Â³ 3 GÃ©nesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),Â¡Three Amigos! (1986),Ã€ nous la libertÃ© (Freedom for Us) (1931)
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Hellboy': The Seeds of Creation (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Round Midnight (1986),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Salem's Lot (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Til There Was You (1997),NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
corr_matrix = user_ratings.corr(method='pearson', min_periods=100)
corr_matrix

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]Â² (2009),[REC]Â³ 3 GÃ©nesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),Â¡Three Amigos! (1986),Ã€ nous la libertÃ© (Freedom for Us) (1931)
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Hellboy': The Seeds of Creation (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Round Midnight (1986),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Salem's Lot (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Til There Was You (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
eXistenZ (1999),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xXx (2002),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xXx: State of the Union (2005),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Â¡Three Amigos! (1986),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ã€ nous la libertÃ© (Freedom for Us) (1931),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
user_ratings

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]Â² (2009),[REC]Â³ 3 GÃ©nesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),Â¡Three Amigos! (1986),Ã€ nous la libertÃ© (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.5,3.5,NaN,NaN,NaN
609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,...,NaN,4.0,3.5,3.0,NaN,NaN,2.0,1.5,NaN,NaN